# This script is to help me learn array indexing in python

In [95]:
import numpy as np

In [96]:
a = np.array([1,2,3])
b = np.array([(1,2,3), (4,5,6)])
c = np.array([[(1,2,3), (4,5,6)], [(7,8,9), (10,11,12)]], dtype = float)

In [97]:
a

array([1, 2, 3])

In [98]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [99]:
c

array([[[  1.,   2.,   3.],
        [  4.,   5.,   6.]],

       [[  7.,   8.,   9.],
        [ 10.,  11.,  12.]]])

In [100]:
c.shape

(2, 2, 3)

In [101]:
c.size

12

In [102]:
c.ndim

3

In [103]:
b.shape


(2, 3)

In [104]:
a.shape

(3,)

In [105]:
d = b.reshape(3,2)
d

array([[1, 2],
       [3, 4],
       [5, 6]])

In [106]:
d.shape

(3, 2)

## why can't I concatenate along elements with same dimension? 

In [107]:
e = np.concatenate((a,d),axis=0)
e

ValueError: all the input arrays must have same number of dimensions

In [108]:
f = np.vstack((a,b))
f

array([[1, 2, 3],
       [1, 2, 3],
       [4, 5, 6]])

In [109]:
c[1,1,1]

11.0

In [110]:
c[0,0,0]

1.0

In [111]:
c[:]

array([[[  1.,   2.,   3.],
        [  4.,   5.,   6.]],

       [[  7.,   8.,   9.],
        [ 10.,  11.,  12.]]])

In [112]:
c[0,:]

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])

In [113]:
c[:,0]

array([[ 1.,  2.,  3.],
       [ 7.,  8.,  9.]])

In [114]:
c.shape

(2, 2, 3)

In [115]:
c[:,:,0]

array([[  1.,   4.],
       [  7.,  10.]])

In [116]:
c[0,0,:]

array([ 1.,  2.,  3.])

In [117]:
c[c<4]

array([ 1.,  2.,  3.])

In [118]:
c[0,0,0]=10
c[c<4]

array([ 2.,  3.])

In [119]:
c_out = c[c>4]
c_out

array([ 10.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,  12.])

In [120]:
c

array([[[ 10.,   2.,   3.],
        [  4.,   5.,   6.]],

       [[  7.,   8.,   9.],
        [ 10.,  11.,  12.]]])

In [136]:
import math
it = 0
ix = 0
iy = 0
wind_spd = c
wind_spd[it,ix,iy] = np.array(math.sqrt(c[it,ix,iy]**2 + c[it,ix,iy]**2))
wind_spd

array([[[ 14.14213562,   2.        ,   3.        ],
        [  4.        ,   5.        ,   6.        ]],

       [[  7.        ,   8.        ,   9.        ],
        [ 10.        ,  11.        ,  12.        ]]])

In [137]:
wind_spd

array([[[ 14.14213562,   2.        ,   3.        ],
        [  4.        ,   5.        ,   6.        ]],

       [[  7.        ,   8.        ,   9.        ],
        [ 10.        ,  11.        ,  12.        ]]])

In [140]:
c


array([[[ 14.14213562,   2.        ,   3.        ],
        [  4.        ,   5.        ,   6.        ]],

       [[  7.        ,   8.        ,   9.        ],
        [ 10.        ,  11.        ,  12.        ]]])